### ISSUE TITLE
data source ami query does not return any results

### ISSUE THREAD

**Issue by BradleyYeo** [hashicorp/learn-terraform-aws-asg#11]
╷
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with data.aws_ami.amazon-linux,
│   on main.tf line 28, in data "aws_ami" "amazon-linux":
│   28: data "aws_ami" "amazon-linux" {
│ 
╵

**Comment by ritsok** [comment]
Pushing a fix, thanks!
